name: sports_private_pool
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.0
  cloud_firestore: ^0.13.4+2
  cloud_functions: ^0.5.0
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  firebase_core: ^0.4.4+3
  firebase_dynamic_links: ^0.5.3
  google_sign_in: ^4.4.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.1
  http: ^0.12.0+4
  instant: ^0.4.1
  path_provider: ^1.6.11
  provider: ^4.1.3
  random_string: ^2.0.1
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  webview_flutter: ^2.0.4
  razorpay_flutter: ^1.2.5
  fluttertoast: ^8.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/icons8-home.png
    - images/icons/icons8-plus.png
    - images/icons/icons8-user.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
