name: sports_private_pool
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.6
  cloud_functions: ^3.2.5
  cupertino_icons: ^1.0.4
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_dynamic_links: ^4.0.4
  firebase_messaging: ^11.2.5
  flutter_local_notifications: ^9.2.0
  flutter_svg: ^1.0.3
  google_nav_bar: ^5.0.5
  google_sign_in: ^5.2.3
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  instant: ^0.4.1
  path_provider: ^2.0.8
  provider: ^6.0.2
  random_string: ^2.3.1
  share: ^2.0.4
  shared_preferences: ^2.0.12
  webview_flutter: ^3.0.0
  line_icons: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/icons8-home.png
    - images/icons/icons8-plus.png
    - images/icons/icons8-user.png
    - images/icons/paytm.svg

  fonts:
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 400
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 900
        - asset: fonts/SourceSansPro-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 800
        - asset: fonts/SourceSansPro-BoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Open Sans
      fonts:
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/OpenSans-Light.ttf
          weight: 300
        - asset: fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
