name: sports_private_pool
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  cloud_firestore: ^0.13.4+2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.0
  http: ^0.12.0+4
  random_string: ^2.0.1
  provider: ^4.1.3
  hive: ^1.4.1+1
  path_provider: ^1.6.11
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12+4
  firebase_dynamic_links: ^0.5.3
  share: ^0.6.5+4


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.4

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/icons8-home.png
    - images/icons/icons8-plus.png
    - images/icons/icons8-user.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

